### ISSUE TITLE
Visualize Impact reduction

### ISSUE THREAD

**Issue by Mq89** [INCYDE-GmbH/drawio-plugin-attackgraphs#104]
Edges with Impacts should be enabled to visualize Impact reduction in the same way as nodes show reduction in their attributes (blue strikethrough).

How much effort would it be to implement this?

**Comment by tobi18991** [comment]
In theory, it shouldn't be difficult. I will probably have to define a new edge type (a new shape) in order to manipulate how an edge will be rendered. However, this will of cause result in the fact that older versions of the plugin cannot show the new edge type in graphs and old attack graphs with regular edges won't show the reduction.

Before I will implement this new feature, I will have a look on whether it is possible to manipulate the rendering of an edge without defining a new type to make it compatible with other versions of the plugin. Yet, I cannot guarantee that I find something like that or if this is even possible.

**Comment by Mq89** [comment]
Ok, please have a look.
