### ISSUE TITLE
Create file from template URL does not work.

### ISSUE THREAD

**Issue by Mq89** [INCYDE-GmbH/drawio-plugin-attackgraphs#157]
Following the instructions to open a new file from a template shows no effect.
The template behind the pasted URL is not presented in the dialog.

https://github.com/INCYDE-GmbH/drawio-plugin-attackgraphs/blob/7e2a92cd3a5828812b57221ba926f0d60ce61abb/docs/index.md?plain=1#L19-L26

**Comment by tobi18991** [comment]
Under which circumstances does this happen?

In the [browser app](https://incyde-gmbh.github.io/drawio-plugin-attackgraphs/app/), importing the template via the links works. I can also select either the RKL or the TS50701 template:
![New diagram dialog](https://github.com/user-attachments/assets/3cc9dbec-ba60-4090-a9c1-9173d6ee4668)

With the desktop version, I cannot import the templates via the link ("Forbidden" dialog), but this is probably due to the Content Security Policy or similar. The templates are not shown in the dialog as we have no control over the embedded templates in the desktop version.

**Comment by Mq89** [comment]
Sorry, I was talking about the desktop version.

Maybe it is sufficient to clarify in the documentation that this does not work in the desktop version.
On the other hand, in the browser app, there is no need to paste URLs as the tamplates are provided out of the box.

I think I can come up with an improved description of the documentation to solve this issue.

**Comment by tobi18991** [comment]
Closed by #163
