### ISSUE TITLE
Global attributes and functions should be available on every page of a diagram

### ISSUE THREAD

**Issue by Mq89** [INCYDE-GmbH/drawio-plugin-attackgraphs#6]
Global attributes and functions should be available on every page of a diagram.

This refers to multiple diagrams in a single `.drawio` file.

**Comment by tobi18991** [comment]
This issue is rather complex and will require more sophisticated changes made to the code. Right now, the plugin only accesses and manipulates the opened page and not the others. As the changes to solve the issue require the attributes and functions to be saved outside of the diagrams (pages), this won't be solved easily.

As I'm not experienced in developing draw.io plugins, maybe someone else is better suited to solve this issue?
