### ISSUE TITLE
Open AttackGraph causes error

### ISSUE THREAD

**Issue by Mq89** [INCYDE-GmbH/drawio-plugin-attackgraphs#99]
![grafik](https://user-images.githubusercontent.com/4853357/210330737-e4426c1a-10a6-48d2-a743-25abbf677d24.png)

Present in at least diagrams.net 20.7.4 (Desktop).

After pressing "OK" plugin works as expected.

**Comment by tobi18991** [comment]
Are you using the web version of draw.io or the desktop version? I tried to load the plugin in the web version with diagrams.net 20.7.4 and the plugin cannot even be enabled in my case...

**Comment by Mq89** [comment]
> Are you using the web version of draw.io or the desktop version?

Desktop. Updated the initial description as well.

**Comment by tobi18991** [comment]
The problem seems to be related with the Sidebar and how we add the "Attack Graphs" palette to it. To resolve this issue, I will have a look into how draw.io handles the sidebar now and hopefully find the change that introduced this problem.

**Comment by tobi18991** [comment]
The error is renderer by `Sidebar.removePalette()` -- a draw.io function. However, since the UI was refactored in diagrams.net version 20.6.0, the container for the sidebar is now a wrapper for the old container and a new footer ("More Shapes" button). The old `removePalette()` function is not yet updated for this new DOM strcuture. Hence, the error is emitted.

We now have a dilemma to solve: If I update our Sidebar code, it will work beginning with diagramms.net version 20.6.0 but fails for older versions. However, our self-hosted (GitHub Pages) web version is fixed to 20.2.8 because the plugins are by default disabled in newer versions.

@Mq89 What is your opinion on how we resolve this issue? I'm still trying to find a more backwards-compatible fix. The main problem currently is that we want our "Attack Graphs" palette to be shown as the first element in the sidebar. However, the current resorting requires manual "swaps" in the DOM strcuture that changed in 20.6.0...

**Comment by Mq89** [comment]
How much effort would it be to do two different things depending on the version of diagrams.net?
Do "A" if version < 20.6.0 and do "B" if version >= 20.6.0?

The thing I currently do is have the latest version of diagrams.net installed on my system for "normal" use without AttackGraphs. If I want to do something with AttackGraphs, I use the "No Installer" executable of [19.0.2](https://github.com/jgraph/drawio-desktop/releases/tag/v19.0.2).
The just don't run simulateneously (whichever version is started first runs in any new window).
So we could also write in the documentation that the desktop version is only supported until v19.0.2. And not above.

**Comment by tobi18991** [comment]
The problem is that I'm not able yet to access the currently used version of draw.io in the plugin. Otherwise, this would be a very easy fix...

The documentation ([GitHub Page](https://incyde-gmbh.github.io/drawio-plugin-attackgraphs/)) already includes the hint for the desktop version. However, we can also include that in the README (and realease notes) as well.
